[mypy]
strict = True
python_version = 3.12
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
disallow_any_unimported = False
disallow_any_expr = False
disallow_any_decorated = False
disallow_any_explicit = False

[mypy-bot.__init__]
ignore_errors = True

[mypy-customer_bot.data.*]
ignore_errors = True
