#!/usr/bin/env node
/**
 * research_agent.js — Multi-Session AI Research Agent
 * 
 * Uses DeepSeek API for deep research/analysis.
 * Saves findings to memory/research/ for future reference.
 * 
 * Usage:
 *   node research_agent.js "research query" [--timeout 300] [--model deepseek]
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

const DEEPSEEK_KEY = process.env.DEEPSEEK_API_KEY;
if (!DEEPSEEK_KEY) {
  console.error("❌ DEEPSEEK_API_KEY not set in environment");
  process.exit(1);
}

const args = process.argv.slice(2);
let query = '';
let timeout = 120;

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--timeout') { timeout = parseInt(args[i+1]) || 120; i++; }
  else { query = args[i]; }
}

if (!query) {
  console.log("Usage: node research_agent.js 'query' [--timeout 120]");
  console.log("Example: node research_agent.js 'Latest PS5 game releases 2026'");
  process.exit(1);
}

async function research() {
  console.log(`\n🔬 Research Agent — "${query.substring(0, 80)}..."`);
  console.log(`   Model: DeepSeek V4 Pro | Timeout: ${timeout}s\n`);
  
  const startTime = Date.now();
  
  try {
    const systemPrompt = `You are Kora's Research Agent — a specialized sub-agent for deep research.
Guidelines:
- Provide comprehensive, accurate answers
- Use bullet points, sections, and tables for clarity
- Include practical implementation details for technical queries
- Be objective and cite specific facts
- When uncertain, say so — never hallucinate
- Keep responses well-structured and readable`;

    const result = await callDeepSeek(systemPrompt, query, timeout);
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
    
    console.log(`\n📊 Research Complete (${elapsed}s)`);
    console.log(`${'═'.repeat(60)}`);
    console.log(result);
    console.log(`${'═'.repeat(60)}`);
    
    // Save to file
    const safeName = query.replace(/[^a-zA-Z0-9\u1000-\u109f]/g, '_').substring(0, 50);
    const outPath = path.join(__dirname, 'memory', 'research', `${safeName}_${Date.now()}.md`);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    
    fs.writeFileSync(outPath, [
      `# Research: ${query}`,
      `**Date:** ${new Date().toISOString()}`,
      `**Source:** DeepSeek V4 Pro`,
      `**Duration:** ${elapsed}s`,
      ``,
      result,
      ``,
      `---\n*Generated by Research Agent*`,
    ].join('\n'));
    
    console.log(`\n💾 Saved to: ${outPath}`);
    
  } catch (err) {
    console.error(`\n❌ Research failed: ${err.message}`);
    process.exit(1);
  }
}

function callDeepSeek(systemPrompt, userQuery, timeoutSec) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model: "deepseek-v4-pro",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userQuery }
      ],
      max_tokens: 4096,
      temperature: 0.3,
      stream: false,
    });

    const options = {
      hostname: "api.deepseek.com",
      path: "/v1/chat/completions",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${DEEPSEEK_KEY}`,
      },
      timeout: timeoutSec * 1000,
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on("data", (chunk) => data += chunk);
      res.on("end", () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.error) {
            reject(new Error(parsed.error.message || "API error"));
            return;
          }
          const text = parsed.choices?.[0]?.message?.content || "No response";
          resolve(text);
        } catch (e) {
          reject(new Error(`Parse error: ${e.message}`));
        }
      });
    });

    req.on("error", reject);
    req.on("timeout", () => { req.destroy(); reject(new Error("Timeout")); });
    req.write(body);
    req.end();
  });
}

research();
