const { Client } = require('ssh2');
const fs = require('fs');

const host = '167.71.196.120';
const BOT_DIR = '/root/Sales-Tele-Bot_refactored';
const data = JSON.parse(fs.readFileSync('/home/node/.openclaw/workspace/audit_data.json', 'utf8'));

function execCmd(conn, cmd) {
  return new Promise((resolve, reject) => {
    conn.exec(cmd, (err, stream) => {
      if (err) return reject(err);
      let stdout = '', stderr = '';
      stream.on('data', d => stdout += d.toString());
      stream.stderr.on('data', d => stderr += d.toString());
      stream.on('close', code => resolve({ stdout: stdout.trim(), stderr: stderr.trim(), code }));
    });
  });
}

function writeFile(conn, remotePath, content) {
  return new Promise((resolve, reject) => {
    conn.sftp((err, sftp) => {
      if (err) return reject(err);
      const buf = Buffer.from(content, 'utf8');
      const stream = sftp.createWriteStream(remotePath, { mode: 0o644 });
      stream.on('error', reject);
      stream.on('close', resolve);
      stream.write(buf);
      stream.end();
    });
  });
}

// ====== BUILD CONSISTENCY_AUDIT.md ======
function buildConsistencyMd() {
  const allStates = [...new Set([...data.appStatesArr, ...data.handlerStates])].sort();
  const allBtns = [...new Set([...data.btnDefined, ...data.btnUsed])].sort();

  let md = `# Consolidated Consistency Audit

Generated: 2026-05-27

---

## Check 1: Handler Return States vs app.py State Registry

### Full State Table

| # | State | Defined in app.py? | Returned by Handler? | Status |
|---|-------|--------------------|---------------------|--------|
`;
  let idx = 1;
  for (const s of allStates) {
    const inApp = data.appStatesArr.includes(s);
    const inHandler = data.handlerStates.includes(s);
    let status;
    if (inApp && inHandler) status = '✅ OK';
    else if (!inApp && inHandler) status = '❌ Handler only (missing from app.py)';
    else if (inApp && !inHandler) status = '⚠️ Unused state (no handler returns it)';
    md += `| ${idx++} | \`${s}\` | ${inApp ? '✅ Yes' : '❌ No'} | ${inHandler ? '✅ Yes' : '❌ No'} | ${status} |\n`;
  }

  md += `\n### Summary

- **Total unique states referenced:** ${allStates.length}
- **States defined in app.py:** ${data.appStatesArr.length}
- **States returned directly by handlers:** ${data.handlerStates.length}
- **Handler-only states (missing from app.py):** ${data.statesInHandlersNotApp.length}
`;
  if (data.statesInHandlersNotApp.length > 0) {
    for (const s of data.statesInHandlersNotApp) {
      md += `  - ❌ \`${s}\` — returned by a handler but NOT listed in app.py states dict\n`;
    }
  }
  md += `- **Unused states (in app.py, no handler returns them directly):** ${data.statesInAppNotHandlers.length}
`;
  if (data.statesInAppNotHandlers.length > 0) {
    for (const s of data.statesInAppNotHandlers) {
      md += `  - ⚠️ \`${s}\` — defined in app.py but no handler directly returns it\n`;
    }
  }

  md += `\n### Indirect State Returns via show_* Functions

The following show_* functions are called by handlers and return states indirectly. These ARE mapped in app.py:

`;
  const showFuncs = data.showFunctions.split('\n').filter(Boolean);
  for (const f of showFuncs) {
    md += `- \`${f}\`\n`;
  }

  md += `\n---

## Check 2: BTN Constants — Defined vs Used

### Full BTN Table

| # | BTN Constant | Defined in \`__init__.py\`? | Used in \`handlers/\`? | Status |
|---|-------------|------------------------|--------------------|--------|
`;
  idx = 1;
  for (const b of allBtns) {
    const defined = data.btnDefined.includes(b);
    const used = data.btnUsed.includes(b);
    let status;
    if (defined && used) status = '✅ OK';
    else if (defined && !used) status = '⚠️ Defined but never used';
    else status = '❌ Used but never defined';
    md += `| ${idx++} | \`${b}\` | ${defined ? '✅' : '❌'} | ${used ? '✅' : '❌'} | ${status} |\n`;
  }

  md += `\n### Summary

- **Total unique BTN constants referenced:** ${allBtns.length}
- **Defined in \`bot/__init__.py\`:** ${data.btnDefined.length}
- **Used in \`handlers/\`:** ${data.btnUsed.length}
- **Defined but unused (candidates for cleanup):** ${data.btnDefinedNotUsed.length}
`;
  if (data.btnDefinedNotUsed.length > 0) {
    for (const b of data.btnDefinedNotUsed) {
      md += `  - ⚠️ \`${b}\`\n`;
    }
  }
  md += `- **Used but not defined (missing imports/defs):** ${data.btnUsedNotDefined.length}
`;
  if (data.btnUsedNotDefined.length > 0) {
    for (const b of data.btnUsedNotDefined) {
      md += `  - ❌ \`${b}\`\n`;
    }
  }

  md += `\n---
*Generated by consolidated V2 audit (subagent) on 2026-05-27*\n`;
  return md;
}

// ====== BUILD SALES_FLOW_AUDIT.md ======
function buildSalesFlowMd() {
  const analysisLines = data.salesAnalysis.split('\n').filter(Boolean);
  const replitLines = data.replitCalls.split('\n').filter(Boolean);
  const apiLines = data.apiEndpoints.split('\n').filter(Boolean);
  const funcLines = data.salesFunctions.split('\n').filter(Boolean);
  const sheetLines = data.sheetOps.split('\n').filter(Boolean);

  // Parse analysis sections
  const sections = {};
  let currentSection = '';
  for (const line of analysisLines) {
    if (line.startsWith('=== ')) {
      currentSection = line.replace(/^=== /, '').replace(/ ===$/, '').trim();
      sections[currentSection] = [];
    } else if (currentSection) {
      sections[currentSection].push(line);
    }
  }

  let md = `# Sales Flow Audit

Generated: 2026-05-27

---

## 1. Step-by-Step Sales Flow (\`step_sale_confirm\` → \`_sale_bg\`)

The sales entry point is \`step_sale_confirm()\` (line 812 in \`bot/handlers/sales.py\`).  
After user confirmation, it spawns \`_sale_bg()\` (inner function at line 976) as an async background task.

### Flow Sequence

| Step | Line | Action | Details |
|------|------|--------|---------|
| 1 | 812 | \`step_sale_confirm\` entry | Receives user confirmation text |
| 2 | ~820 | Parse sale data | Extracts \`m_id\`, \`c_id\`, \`play_mins\`, prices, food items, discounts from context.user_data |
| 3 | ~940 | Check if linked booking exists | Reads \`d.get("booking_id", "")\` |
| 4 | ~960 | Calculate totals | Computes \`net_total\`, \`game_amt\`, \`food_total\`, \`_disc\`, \`_w_deduct\` |
| 5 | 976 | **\`_sale_bg()\`** inner function defined | Nested async function for background sheet writes |
| 6 | 979-984 | \`_do()\` ↔ \`sales_sh.batch_update\` → **Cols A–K, N, O** | Writes sale row to Sales_Daily |
| 7 | 990 | \`stock_sh.append_row\` (per food item) | Logs food inventory deduction |
| 8 | 997-1000 | \`_replit_get\` + \`_replit_post\` | Refreshes inventory, logs promotion if applied |
| 9 | 1004-1018 | Bonus minutes → \`member_sh.update_cell\` | Adds bonus mins to member wallet (Col 8) |
| 10 | 1030 | \`asyncio.create_task(_sale_bg())\` | Fires the background write |
| 11 | 1033-1044 | Booking marked completed | \`_replit_patch bookings/{id}/status\` |
| 12 | 1048-1059 | Waitlist notify | \`_replit_post waitlist/notify\` |
| 13 | 1062-1081 | Session-end notification | \`_replit_post session-end-notify\` |
| 14 | 1066 | Low balance alert | \`_check_low_balance_alert\` |
| 15 | 1086 | \`return await show_main_menu\` | Returns to MAIN_MENU state |

---

## 2. \`_sale_bg()\` Write Targets (Sales_Daily Sheet)

### Columns Written

| Column | Content | Written in \`_sale_bg\`? | Notes |
|--------|---------|--------------------------|-------|
| **A** | Date (\`today\`) | ✅ | First value in batch_update range A:K |
| **B** | Voucher No (\`v_no\`) | ✅ |  |
| **C** | Member ID (\`_m_id\`) | ✅ |  |
| **D** | Console ID (\`c_id\`) | ✅ |  |
| **E** | Play Minutes (\`play_mins\`) | ✅ |  |
| **F** | Game Amount (\`game_amt\`) | ✅ |  |
| **G** | Food Total (\`food_total\`) | ✅ |  |
| **H** | Discount (\`_disc\`) | ✅ |  |
| **I** | Net Total (\`net_total\`) | ✅ |  |
| **J** | K-Pay Amount (\`kpay\`) | ✅ |  |
| **K** | Cash Amount (\`cash\`) | ✅ |  |
| **L** | *(unused)* | ❌ **NEVER WRITTEN** | Gap — no data mapped to Col L |
| **M** | *(unused)* | ❌ **NEVER WRITTEN** | Gap — no data mapped to Col M |
| **N** | Wallet Deduct Mins (\`_w_deduct\`) | ✅ | Separate \`batch_update\` for range N |
| **O** | Staff Name (\`staff_name\`) | ✅ | Separate \`batch_update\` for range O |

### Sheet Write Operations in Code

`;
  for (const l of sheetLines) {
    md += `- \`${l}\`\n`;
  }

  md += `
### Actual \`batch_update\` Call

The primary write merges ranges \`A{s_row}:K{s_row}\`, \`N{s_row}\`, and \`O{s_row}\` into one \`sales_sh.batch_update()\` call:

\`\`\`
sales_sh.batch_update([
    {"range": f"A{s_row}:K{s_row}",
     "values": [[today, v_no, _m_id, c_id, play_mins,
                game_amt, food_total, _disc, net_total, kpay, cash]]},
    {"range": f"N{s_row}", "values": [[_w_deduct if _w_deduct else ""]]},
    {"range": f"O{s_row}", "values": [[staff_name]]},
], value_input_option="USER_ENTERED")
\`\`\`

---

## 3. \`_replit_*\` Calls in sales.py

`;
  if (replitLines.length === 0) {
    md += `No \`_replit_\` references found.\n`;
  } else {
    for (const l of replitLines) {
      md += `- \`${l}\`\n`;
    }
  }

  md += `
---

## 4. API Endpoints (api_server/server.py)

`;
  if (apiLines.length === 0) {
    md += `No endpoints found in \`api_server/server.py\`.\n`;
  } else {
    for (const l of apiLines) {
      md += `- \`${l}\`\n`;
    }
  }

  md += `
---

## 5. Functions in \`bot/handlers/sales.py\`

\`\`\`
`;
  for (const l of funcLines) {
    md += `${l}\n`;
  }
  md += '```\n';

  md += `
---

## 6. Gaps Found

### Sales_Daily Column Gaps (Col L, Col M)

- **Col L:** This column is **never written** in \`_sale_bg()\`. If the Sales_Daily sheet expects data here (e.g., discount type, referral code, delivery fee), it will remain empty for every sale.
- **Col M:** This column is also **never written**. Same concern.

**Possible intended mapping:** These columns may be reserved for future fields or may have been removed during refactoring. Verify against the actual sheet header row.

### Handler States Missing from app.py

- \`NM_STAFF\` — returned by a handler but not registered in app.py's \`states={}\`
- \`STAFF_SELECT\` — same issue

These will cause \`InvalidConversationState\` errors if triggered.

### Unused BTN Constants (13 total)

Cleanup candidates: \`BTN_ADD_PAY\`, \`BTN_ATTEND_NEXT\`, \`BTN_CANCEL_BOOKING\`, \`BTN_CONSOLE_BOOK\`, \`BTN_CONSOLE_STATUS\`, \`BTN_NO_BACK\`, \`BTN_NO_MORE\`, \`BTN_PAY_DONE\`, \`BTN_SAVE\`, \`BTN_SBK_TODAY\`, \`BTN_SBK_TOMORROW\`, \`BTN_SKIP_PHONE\`, \`BTN_YES_END\`

### Missing BTN Definitions (6 total)

These are used in handlers but not defined in \`bot/__init__.py\`:

- \`BTN_DISC_MGMT\` — used but missing
- \`BTN_FOOD_SETUP\`
- \`BTN_GAMES\`
- \`BTN_SSD_DISC\`
- \`BTN_STOCK_MGMT\`
- \`BTN_TO_ID\`

These may cause \`NameError\` at runtime.

---

*Generated by consolidated V2 audit (subagent) on 2026-05-27*\n`;
  return md;
}

(async () => {
  const conn = new Client();
  await new Promise((resolve, reject) => {
    conn.on('ready', resolve).on('error', reject);
    conn.connect({
      host, username: 'root',
      privateKey: fs.readFileSync('/home/node/.openclaw/workspace/.ssh/id_rsa', 'utf8')
    });
  });

  const consistencyMd = buildConsistencyMd();
  const salesMd = buildSalesFlowMd();

  console.log('=== Writing CONSISTENCY_AUDIT.md ===');
  await writeFile(conn, `${BOT_DIR}/CONSISTENCY_AUDIT.md`, consistencyMd);
  const verify1 = await execCmd(conn, `wc -l ${BOT_DIR}/CONSISTENCY_AUDIT.md`);
  console.log('Lines:', verify1.stdout);

  console.log('=== Writing SALES_FLOW_AUDIT.md ===');
  await writeFile(conn, `${BOT_DIR}/SALES_FLOW_AUDIT.md`, salesMd);
  const verify2 = await execCmd(conn, `wc -l ${BOT_DIR}/SALES_FLOW_AUDIT.md`);
  console.log('Lines:', verify2.stdout);

  console.log('=== Appending to AGENT_STATUS.md ===');
  await execCmd(conn, `echo "consolidated_audit_fast=done" >> ${BOT_DIR}/AGENT_STATUS.md`);

  const verify3 = await execCmd(conn, `ls -la ${BOT_DIR}/CONSISTENCY_AUDIT.md ${BOT_DIR}/SALES_FLOW_AUDIT.md ${BOT_DIR}/AGENT_STATUS.md`);
  console.log('\n=== Verification ===');
  console.log(verify3.stdout);

  conn.end();
  console.log('\n=== ALL DONE ===');
})().catch(err => { console.error('FATAL:', err); process.exit(1); });
