#!/usr/bin/env python3
"""
Deploy Daily Sales to Telegram notification system.
Creates a cron job that sends yesterday's sales summary every morning.
"""
import json
import os
import subprocess
import sys

SALES_BOT_DIR = "/root/psvibe-sales-bot"
API_URL = "https://ps-vibe.com/api"
CRON_FILE = "/etc/cron.d/kora-daily-sales"

def check_api():
    """Test API connectivity"""
    import urllib.request
    try:
        req = urllib.request.Request(f"{API_URL}/sales/today")
        resp = urllib.request.urlopen(req, timeout=10)
        data = json.loads(resp.read())
        print(f"✅ API OK — {len(data.get('data',[])) if isinstance(data,dict) else '?'} records")
        return True
    except Exception as e:
        print(f"⚠️ API test: {e}")
        return False

def create_summary_script():
    """Create the daily sales summary generator"""
    script = '''#!/usr/bin/env python3
"""Daily Sales Summary — generated by Kora"""
import json, urllib.request, os
from datetime import datetime, timedelta, timezone

API = "https://ps-vibe.com/api"
MMT = timezone(timedelta(hours=6, minutes=30))

yesterday = (datetime.now(MMT) - timedelta(days=1)).strftime("%Y-%m-%d")
today = datetime.now(MMT).strftime("%Y-%m-%d")

def get(endpoint):
    req = urllib.request.Request(f"{API}/{endpoint}")
    try:
        resp = urllib.request.urlopen(req, timeout=15)
        return json.loads(resp.read())
    except: return {}

# Sales
sales = get(f"sales/date?date={yesterday}")
sale_items = sales.get("data", sales.get("rows", [])) if isinstance(sales, dict) else []
total_sales = sum(float(r.get("total_amount", r.get("amount", 0))) for r in (sale_items if isinstance(sale_items, list) else []))

# Topups
topups = get(f"topups/date?date={yesterday}")
topup_items = topups.get("data", topups.get("rows", [])) if isinstance(topups, dict) else []
total_topups = sum(float(r.get("amount", 0)) for r in (topup_items if isinstance(topup_items, list) else []))

# Members
members = get("members/count") 
member_count = 0
if isinstance(members, dict):
    member_count = members.get("count", members.get("data", 0))

# Format
msg = f"📊 PS VIBE Daily Summary — {yesterday}\\n\\n"
msg += f"💰 Sales: {total_sales:,.0f} Ks\\n"
msg += f"💳 Topups: {total_topups:,.0f} Ks\\n"
msg += f"👥 Members: {member_count}\\n"
msg += f"📅 Total: {total_sales + total_topups:,.0f} Ks\\n\\n"
msg += f"🤖 Kora — Daily Auto-Report"

# Save for cron to pick up
output_path = "/tmp/kora_daily_sales.txt"
with open(output_path, "w") as f:
    f.write(msg)
print(f"✅ Daily sales summary saved ({total_sales:,.0f} + {total_topups:,.0f} = {total_sales+total_topups:,.0f} Ks)")
'''
    path = f"{SALES_BOT_DIR}/daily_sales_summary.py"
    with open(path, "w") as f:
        f.write(script)
    os.chmod(path, 0o755)
    print(f"✅ Created {path}")
    return path

def test_script(script_path):
    """Test the summary script"""
    result = subprocess.run(["python3", script_path], capture_output=True, text=True, timeout=15)
    print(result.stdout.strip())
    if result.returncode == 0:
        print("✅ Script test passed")
        # Show what was generated
        output_path = "/tmp/kora_daily_sales.txt"
        if os.path.exists(output_path):
            with open(output_path) as f:
                print(f"\n📋 Generated message:\n{f.read()}")
        return True
    else:
        print(f"❌ Script error: {result.stderr[:200]}")
        return False

def main():
    print("🚀 Deploying Daily Sales to Telegram...")
    
    # 1. Check API
    api_ok = check_api()
    
    # 2. Create summary script
    script_path = create_summary_script()
    
    # 3. Test it
    test_ok = test_script(script_path)
    
    if api_ok and test_ok:
        print("\n✅ Daily Sales system ready!")
        print("\n📌 Next step: Create cron job to send to Telegram every morning")
    else:
        print("\n⚠️ Some checks failed — review output above")

if __name__ == "__main__":
    main()
