#!/usr/bin/env python3
"""
Deploy Daily Sales to Telegram — uses MySQL directly for data
"""
import os, subprocess, json

SALES_BOT_DIR = "/root/psvibe-sales-bot"

def create_script():
    script = '''#!/usr/bin/env python3
"""Daily Sales Summary — generated by Kora (MySQL)"""
import os, json, pymysql
from datetime import datetime, timedelta, timezone

MMT = timezone(timedelta(hours=6, minutes=30))
now = datetime.now(MMT)
yesterday = (now - timedelta(days=1)).strftime("%Y-%m-%d")

# MySQL connection (via Docker)
conn = pymysql.connect(
    host="127.0.0.1", port=3306,
    user="psvibe_user", password="PSV_P@ssw0rd",
    database="psvibe_db",
    cursorclass=pymysql.cursors.DictCursor
)
cur = conn.cursor()

# Today sales
cur.execute("SELECT COALESCE(SUM(amount),0) as total FROM sales_daily WHERE DATE(created_at)=%s", (yesterday,))
total_sales = cur.fetchone()["total"]

# Topups
cur.execute("SELECT COALESCE(SUM(amount),0) as total FROM topup_log WHERE DATE(created_at)=%s AND status='completed'", (yesterday,))
total_topups = cur.fetchone()["total"]

# Member count
cur.execute("SELECT COUNT(*) as c FROM members WHERE rank != 'DELETED'")
member_count = cur.fetchone()["c"]

# Top games yesterday
cur.execute("""
    SELECT g.name, COUNT(*) as cnt, SUM(sf.amount) as rev
    FROM sales_daily sf
    JOIN games g ON sf.game_id = g.id
    WHERE DATE(sf.created_at)=%s AND sf.game_id IS NOT NULL
    GROUP BY g.name ORDER BY rev DESC LIMIT 5
""", (yesterday,))
top_games = cur.fetchall()

# Active sessions right now
cur.execute("SELECT COUNT(*) as c FROM console_status WHERE status='occupied'")
active = cur.fetchone()["c"]

cur.close(); conn.close()

# Build message
msg = f"📊 PS VIBE Daily Summary — {yesterday}\\n"
msg += "━" * 25 + "\\n"
msg += f"💰 **Sales:** {total_sales:,.0f} Ks\\n"
msg += f"💳 **Topups:** {total_topups:,.0f} Ks\\n"
msg += f"👥 **Members:** {member_count}\\n"
msg += f"🎮 **Active Now:** {active}\\n\\n"

if top_games:
    msg += "🏆 **Top Games:**\\n"
    for i, g in enumerate(top_games[:3], 1):
        msg += f"  {i}. {g['name']} — {g['rev']:,.0f} Ks\\n"

msg += f"\\n📈 **Total Revenue:** {total_sales+total_topups:,.0f} Ks\\n"
msg += f"🤖 *Kora — Daily Auto-Report*"

# Save for cron
path = "/tmp/kora_daily_sales.txt"
with open(path, "w") as f:
    f.write(msg)
print(msg)
print(f"\\n✅ Saved to {path}")
'''
    path = f"{SALES_BOT_DIR}/daily_sales_summary.py"
    with open(path, "w") as f:
        f.write(script)
    os.chmod(path, 0o755)
    print(f"✅ Created {path}")
    return path

def test(script_path):
    result = subprocess.run(["python3", script_path], capture_output=True, text=True, timeout=20)
    print(result.stdout.strip())
    if result.returncode != 0:
        print(f"❌ Error: {result.stderr[:300]}")

if __name__ == "__main__":
    print("🚀 Deploying v2 Daily Sales (MySQL)...")
    p = create_script()
    test(p)
